### ISSUE TITLE
Step 3. Training -> Building the Container

### ISSUE THREAD

**Issue by daleangus** [googlecodelabs/kubeflow-introduction#2]
Running this in cloud shell.

**docker build -t $TRAIN_PATH ./tensorflow-model       --build-arg version=$VERSION_TAG --build-arg bucket=$BUCKET_NAME**   

FAILS with 

**"unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /home/angusdale/tensorflow-model/Dockerfile: no such file or directory"**

I tried "lstat" and got "-bash: lstat: command not found"

**Comment by DanSanche** [comment]
This command should be run from within the repo root directory. It looks like this is being run from your home folder
